# Few-Shot Classification Config
# Data
num_shots: 16
base_path: "/home/mrapo/data/few-shot-classification"
dataset: "???"
dataset_seed: 0
# Reward
task_lm: "roberta-large"
is_mask_lm: null
prompt: "???"
